"""Render the public schema reference and exhaustive offline migration table."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from qqbot.configuration.schema import Settings
from scripts.migrations.config_v1 import MANIFEST, field_rules


def schema_fields():
    schema = Settings.model_json_schema()

    def walk(node, prefix=""):
        if "$ref" in node:
            node = schema["$defs"][node["$ref"].rsplit("/", 1)[1]]
        for name, spec in node["properties"].items():
            path = f"{prefix}.{name}" if prefix else name
            if "$ref" in spec:
                yield from walk(spec, path)
            else:
                yield path, spec

    return tuple(walk(schema))


def _cell(value) -> str:
    return json.dumps(value, ensure_ascii=False).replace("|", "&#124;")


def reference() -> str:
    lines = [
        "# Settings reference",
        "",
        "Generated from the active schema by `python scripts/config_reference.py --write`.",
        "Do not edit this table independently. Defaults are schema defaults; the example may",
        "choose different values. Required backend fields must be supplied. Other sections",
        "may be omitted. All unknown fields are rejected. See [configuration.md](configuration.md)",
        "for ownership, restart and migration semantics.",
        "",
        "| Field | Default | Validation | Meaning |",
        "| --- | --- | --- | --- |",
    ]
    for path, spec in schema_fields():
        default = _cell(spec["default"]) if "default" in spec else "required"
        bounds = []
        for key in ("type", "enum", "const", "minimum", "maximum", "exclusiveMinimum", "minLength"):
            if key in spec:
                bounds.append(f"{key}={_cell(spec[key])}")
        if "anyOf" in spec:
            bounds.append(" or ".join(_cell(item) for item in spec["anyOf"]))
        lines.append(f"| `{path}` | `{default}` | {'; '.join(bounds)} | {spec['description']} |")
    return "\n".join(lines) + "\n"


def migration_table() -> str:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    lines = [
        "# Pre-refactor settings migration",
        "",
        "Generated by `python scripts/config_reference.py --write` from the frozen public",
        "130-field contract. This table contains no deployment values. A retired nondefault",
        "value needs an explicit `--retire <old.path>` decision; it is never silently dropped.",
        "Unknown input keys fail conversion. Retained values are validated by the new schema.",
        "",
        "| Old field | Old default | Disposition | New field | Mechanism |",
        "| --- | --- | --- | --- | --- |",
    ]
    for path, rule in field_rules().items():
        old = manifest[path]
        default = "required" if old["required"] else _cell(old["default"])
        kind = "derived" if rule.derived else "retired" if rule.target is None else "retained"
        target = f"`{rule.target}`" if rule.target else "—"
        lines.append(f"| `{path}` | `{default}` | {kind} | {target} | {rule.reason} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Regenerate the public documents.")
    args = parser.parse_args()
    outputs = {
        ROOT / "docs/configuration-reference.md": reference(),
        ROOT / "docs/configuration-migration.md": migration_table(),
    }
    stale = []
    for path, text in outputs.items():
        if args.write:
            path.write_text(text, encoding="utf-8")
        elif not path.exists() or path.read_text(encoding="utf-8") != text:
            stale.append(path.name)
    if stale:
        print("Outdated configuration documents: " + ", ".join(stale))
        return 1
    print("Configuration reference and migration table match their schemas.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
